const sourceText = {
  titleProject: 'Сейф',
  login: {
    loginLabel: 'Логин',
    passwordLabel: 'Пароль',
    buttonLabel: 'Вход',
    loginError: 'Заполните поле Логин',
    passwordError: 'Заполните поле Пароль'
  },
  device: {
    typeName: 'Тип устройства',
    model: 'Модель',
    imei: 'IMEI',
    imei1: 'IMEI1',
    imei2: 'IMEI2',
    snNumber: 'Инвентарный бух. номер',
    displaySize: 'Размер экрана',
    ppi: 'PPI',
    os: 'OS',
    osVersion: 'Версия OS',
    brand: 'Бренд',
    deleteTitle: 'Удалить устройстово',
    deviceTransferTitle: 'Перечень устройств на сотрудниках, которые более не находятся в подразделении',
    transfer: 'Переместить',
    transferAllTo: 'Переместить все на'
  },
  equipment: {
    receiptDate: 'Дата поступления',
    group: 'Группа',
    employee: 'Сотрудник',
    owner: 'Владелец',
    system: 'Дополнительные характеристики',
    note: 'Примечание',
    temporaryUse: 'Временное пользование',
    changer: 'ФИО Сотрудника',
    dateInventory: 'Дата Инвентаризации',
    type: 'Тип',
    safe: 'Сейф',
    selectAllAvailable: 'Выбрать все доступные',
    inventory: 'Инвентаризация',
    deleted: 'Удаленные',
    saveInventory: 'Сохранить инвентаризацию',
    cancelInventory: 'Отменить инвентаризацию',
    scanQr: 'Отсканировать QRCode',
    filterReset: 'Очистить фильтр',
    inventoryExitTitle: 'Выход из режима инвентаризации',
    inventoryExitBody: 'Данный функционал не поддерживается в режиме инвентаризации. Данные не будут сохранены. Продолжить выход?',
    exit: 'Выйти',
    save: 'Сохранить',
    delete: 'Удалить',
    deleteComment: 'Коментарий при удалении',
    agreementDelete: 'Согласовать удаление',
    agreedDelete: 'Удаление согласовано',
    agreed: 'Согласование',
  },
  user: {
    role: 'Роль',
    simCount: 'Количество SIM',
    deviceCount: 'Количество устройств'
  },
  sim: {
    typeName: 'Тип устройства',
    simNo: "Номер sim",
    msisdn: 'msisdn',
    simOrMSISDN: "Номер sim или MSISDN",
    provisioning: 'provisioning',
    smsGW: 'SMSGW',
    deleteTitle: 'Удалить sim',
    simTransferTitle: 'Перечень SIM на сотрудниках, которые более не находятся в подразделении',
    transfer: 'Переместить',
    transferAllTo: 'Переместить все на'
  },
  log: {
    date: 'Дата',
    level: 'Тип',
    message: 'Сообщение',
    user: 'Сотрудник'
  },
  title: 'Название',
  month: 'Месяц',
  name: 'Имя',
  missed: 'Уволен',
  role: 'Роль',
  orderBy: 'Сортировка по',
  send: 'Отправить',
  yes: 'Да',
  no: 'Нет',
  add: 'Добавить',
  edit: 'Изменить',
  delete: 'Удалить',
  copy: 'Копировать',
  save: 'Сохранить',
  ok: 'OK',
  typeSomething: 'Hапечатайте что-нибудь',
  saved: 'Сохранено',
  clean: 'Очистить',
  version: 'Версия',
  from: 'От',
  to: 'До',
  department: 'Подразделение',
  departments: 'Подразделения',
  noAccess: 'Нет доступа',
  noAttempts: 'Больше нет попыток',
  saveToXlsx: 'В xlsx',
  addDevice: 'Добавление устройства',
  viewDevice: 'Просмотр устройства',
  addSim: 'Добавление sim',
  viewSim: 'Просмотр sim',
  viewLog: 'Просмотр лога',
  startInventoryTitle: 'Начало инветaризации',
  startInventory: 'Начать инветaризацию',
  InventoryStarted: 'Инветоризация начата',
  osesEdit: 'Изменение OS',
  brandsEdit: 'Изменение бренда',
  EquipmentTypesEdit: 'Изменение типов',
  TypeName: 'Тип',
  comment: 'Коментарий',
  exit: 'Выйти',
}

const getSourceText = () => sourceText
export default getSourceText